package com.codeline.ccsb.helper;

public class Constants {

    public final static String SUCCESS = "success";
    public final static String BAD_REQUEST = "BAD REQUEST";
    public final static Integer LOWER_DURATION_RANGE=0;
    public final static Integer UPPER_DURATION_RANGE=300;
    public final static String COURSE_CREATE_REQUEST_COURSE_NAME_NOT_VALID="NAME IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_CATEGORY_NOT_VALID="CATEGORY IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_DURATION_NOT_VALID="DURATION IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_INSTRUCTOR_ID_NOT_VALID="INSTRUCTOR ID IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_MARK_ID_NOT_VALID="MARK ID IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_DEPARTMENT_ID_NOT_VALID="DEPARTMENT ID IS NOT VALID";


    public final static String DEPARTMENT_CREATE_REQUEST_DEPARTMENT_NAME_NOT_VALID="DEPARTMENT NAME IS NOT VALID";
    public final static String DEPARTMENT_CREATE_REQUEST_INSTRUCTOR_ID_NOT_VALID="INSTRUCTOR NAME IS NOT VALID";
    public final static String DEPARTMENT_CREATE_REQUEST_COURSE_ID_NOT_VALID="COURSE ID IS NOT VALID";

    public final static String INSTRUCTOR_CREATE_REQUEST_INSTRUCTOR_NAME_NOT_VALID="INSTRUCTOR NAME IS NOT VALID";
    public final static String INSTRUCTOR_CREATE_REQUEST_DEPARTMENT_ID_NOT_VALID="DEPARTMENT ID IS NOT VALID";
    public final static String INSTRUCTOR_CREATE_REQUEST_COURSE_ID_NOT_VALID="COURSE ID IS NOT VALID";

    public final static String MARK_CREATE_REQUEST_STUDENT_NAME_NOT_VALID="STUDENT NAME IS NOT VALID";
    public final static String MARK_CREATE_REQUEST_GRADE_NOT_VALID="GRADE IS NOT VALID";
    public final static String MARK_CREATE_REQUEST_COURSE_ID_NOT_VALID="COURSE ID IS NOT VALID";


    public final static String STUDENT_CREATE_REQUEST_FIRST_NAME_NOT_VALID="FIRST NAME IS NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_LAST_NAME_NOT_VALID="LAST NAME IS NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_GENDER_NOT_VALID="GENDER IS NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_EMAIL_NOT_VALID="EMAIL IS NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_DATE_OF_BIRTH_NOT_VALID="DATE OF BIRTH IS NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_PHONE_NUMBER_ID_NOT_VALID="PHONE NUMBER ID IS NOT VALID";
    public final static String STUDENT_CREATE_REQUEST_ADDRESS_NOT_VALID="ADDRESS IS NOT VALID";


    public final static String PHON_NUMBER_CREATE_REQUEST_NUMBER_NOT_VALID="NUMBER IS NOT VALID";
    public final static String PHON_NUMBER_CREATE_REQUEST_COUNTRY_CODE_NOT_VALID="COUNTRY CODE IS NOT VALID";
    public final static String PHON_NUMBER_CREATE_REQUEST_IS_LAND_LINE_NOT_VALID="IS LAND LINE IS NOT VALID";
    public final static String PHON_NUMBER_CREATE_REQUEST_STUDENT_ID_NOT_VALID="STUDENT ID IS NOT VALID";

    public final static String ADDRESS_CREATE_REQUEST_HOUSE_NUMBER_NOT_VALID="HOUSE NUMBER IS NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_STREET_NOT_VALID="STREET IS NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_CITY_NOT_VALID="CITY IS NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_STATE_NOT_VALID="STATE IS NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_COUNTRY_NOT_VALID="COUNTRY IS NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_POSTAL_CODE_NOT_VALID="POSTAL CODE IS NOT VALID";
    public final static String ADDRESS_CREATE_REQUEST_STUDENT_ID_NOT_VALID="STUDENT ID IS NOT VALID";

}
