package com.codeline.ccsb.helper;

public class Constants {

    public final static String SUCCESS = "success";
    public final static String BAD_REQUEST = "BAD REQUEST";
    public final static Integer LOWER_DURATION_RANGE=0;
    public final static Integer UPPER_DURATION_RANGE=300;
    public final static String COURSE_CREATE_REQUEST_COURSE_NAME_NOT_VALID="NAME IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_CATEGORY_NOT_VALID="CATEGORY IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_DURATION_NOT_VALID="DURATION IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_INSTRUCTOR_ID_NOT_VALID="INSTRUCTOR ID IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_MARK_ID_NOT_VALID="MARK ID IS NOT VALID";
    public final static String COURSE_CREATE_REQUEST_DEPARTMENT_ID_NOT_VALID="DEPARTMENT ID IS NOT VALID";


    public final static String DEPARTMENT_CREATE_REQUEST_DEPARTMENT_NAME_NOT_VALID="DEPARTMENT NAME IS NOT VALID";
    public final static String DEPARTMENT_CREATE_REQUEST_INSTRUCTOR_ID_NOT_VALID="INSTRUCTOR NAME IS NOT VALID";
    public final static String DEPARTMENT_CREATE_REQUEST_COURSE_ID_NOT_VALID="COURSE ID IS NOT VALID";

    public final static String INSTRUCTOR_CREATE_REQUEST_INSTRUCTOR_NAME_NOT_VALID="INSTRUCTOR NAME IS NOT VALID";
    public final static String INSTRUCTOR_CREATE_REQUEST_DEPARTMENT_ID_NOT_VALID="DEPARTMENT ID IS NOT VALID";
    public final static String INSTRUCTOR_CREATE_REQUEST_COURSE_ID_NOT_VALID="COURSE ID IS NOT VALID";

    public final static String MARK_CREATE_REQUEST_STUDENT_NAME_NOT_VALID="STUDENT NAME IS NOT VALID";
    public final static String MARK_CREATE_REQUEST_GRADE_NOT_VALID="GRADE IS NOT VALID";
    public final static String MARK_CREATE_REQUEST_COURSE_ID_NOT_VALID="COURSE ID IS NOT VALID";
}
